### ISSUE TITLE
Create Food Menu 

### ISSUE THREAD

**Issue by AndreAffonso** [brunobraga95/mive#10]
### Description

The menu component must have the items filtered by the category or by the typed value at the search input. Each item must have a name and a price. The items must be 
selectable and the quantity can be changed.  The menu must also have a button to confirm the order and a content to show the order amount price. 
 
#### Suggestion

Some [Dribbble Food Menu examples](https://dribbble.com/search?q=food+menu) to inspire the design.

### Tasks

* [ ] Create FoodMenu Container
* [ ] Create FoodMenuItem Component
* [ ] Get data from Firebase
* [ ] Create a confirm order button
* [ ] Add a field to display the amount order, like a  simple shopping cart. 

### Discussion
- How the application could sort the items? Should the user choose a filter like Name, Price, the most populars... or we just display sorting by price?

**Comment by brunobraga95** [comment]
I will work on that.

when it comes to sorting, I will add a counter to every food in the menu, and each time a client(regardless of the table) order a food I will increment that counter and it will act as a rank.

we can first sort by this rank and secondly by price.

**Comment by AndreAffonso** [comment]
Great!
