### ISSUE TITLE
Create bill component 

### ISSUE THREAD

**Issue by AndreAffonso** [brunobraga95/mive#9]
### Description

Create the bill component to show the demands at the user and the amount price. 

### Tasks
* [x] Create Bill container
* [x] Create BillItem component
* [ ] Get bill info from firebase and show at the component 

#### Discussion
Initially, the purpose is just showing the items, the individual price and the amount price. In the future, it's a good ideia to show the log of the demands, with the exactly hour that the demand was ordered.

For example:
- 3 x beers - $ 10.00 
If the user click in this row, it will open a modal showing the hour that each beer was ordered. 

I will project the design thinking about this future implementation.
